services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ${ENV_DIR}/watchtower.env
    networks:
      - caddy_default

networks:
  caddy_default:
    name: caddy_default
    external: true
