[uwsgi]
uid = searxng
gid = searxng
workers = 4
threads = 4
chmod-socket = 666
single-interpreter = true
master = true
plugin = python3
lazy-apps = true
enable-threads = 4
module = searx.webapp
pythonpath = /usr/local/searxng/
chdir = /usr/local/searxng/searx/
buffer-size = 8192
